# Generated by Django 4.2.19 on 2025-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_course_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question',
        ),
        migrations.AddField(
            model_name='course',
            name='question',
            field=models.ManyToManyField(related_name='questions', to='polls.question'),
        ),
    ]
