# Generated by Django 4.2.19 on 2025-02-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_course_question_course_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.course'),
        ),
    ]
